blank_issues_enabled: true
contact_links:
  - name: PowerPulse Discussions
    url: https://github.com/blink-zero/powerpulse/discussions
    about: Please ask and answer questions here.
  - name: PowerPulse Security Issues
    url: https://github.com/blink-zero/powerpulse/security/policy
    about: Please report security vulnerabilities here.
